-- drop function [dbo].Remover_ASCII_CHAR
CREATE FUNCTION [VAGAS_DW].Remover_ASCII_CHAR (@STRING VARCHAR(MAX))
RETURNS VARCHAR(MAX)

AS
BEGIN
   
      DECLARE @INICIO TINYINT = 58

	  -- REMOVER CHAR PÓS NUMERAÇÃO (VIDE TABELA ASCII)
      WHILE @INICIO < 255
      BEGIN
        SELECT @STRING = REPLACE(@STRING,CHAR(@INICIO),' ')
        SELECT @INICIO = @INICIO + 1
      END
      
	  SET @INICIO = 0
	  
	  -- REMOVER CHAR PRÉ NUMERAÇÃO (VIDE TABELA ASCII)
	  WHILE @INICIO < 48
      BEGIN
        SELECT @STRING = REPLACE(@STRING,CHAR(@INICIO),' ')
        SELECT @INICIO = @INICIO + 1
      END
	
	SET @STRING = LTRIM(RTRIM(@STRING))
	RETURN(@STRING)
END

-- drop function [dbo].Tratar_String_Percentual
CREATE FUNCTION [VAGAS_DW].Tratar_String_Percentual (@STRING VARCHAR(MAX))
RETURNS VARCHAR(MAX)

AS
BEGIN
   
      DECLARE @INICIO TINYINT = 1,
			  @STRING_CONCATENADA VARCHAR(8000) = '',
			  @STRING_ANTERIOR CHAR(1) 
	  
	  SET @STRING = RTRIM(LTRIM(@STRING))

	  -- REMOVER CHAR PÓS NUMERAÇÃO (VIDE TABELA ASCII)
      WHILE @INICIO <= LEN(@STRING)
      BEGIN
	    SET @STRING_CONCATENADA = @STRING_CONCATENADA + CASE WHEN SUBSTRING(@STRING,@INICIO,1) = '' AND @STRING_ANTERIOR <> '' THEN ',' 
															 ELSE SUBSTRING(@STRING,@INICIO,1) END
		SET @STRING_ANTERIOR = SUBSTRING(@STRING,@INICIO,1)
		--SELECT @STRING_CONCATENADA = @STRING_CONCATENADA + SUBSTRING(@STRING,@INICIO,1)
        SET @INICIO = @INICIO + 1
      END
    
	SET @STRING_CONCATENADA = REPLACE(@STRING_CONCATENADA,' ','')    
	RETURN(@STRING_CONCATENADA)
END

-- DROP FUNCTION [VAGAS_DW].SPLIT_TABELA
CREATE FUNCTION [VAGAS_DW].SPLIT_TABELA(@STRING AS VARCHAR(8000) )
RETURNS
      @RESULTADO TABLE(STRING VARCHAR(8000))
AS
BEGIN
      DECLARE @STRING_CONCATENADA VARCHAR(20)
      DECLARE @INDICE Int

      IF(@STRING IS NOT NULL)
      BEGIN
            SET @INDICE = CHARINDEX(',',@STRING)
            WHILE @INDICE > 0
            BEGIN
                  SET @STRING_CONCATENADA = SUBSTRING(@STRING,1,@INDICE-1)
                  SET @STRING = SUBSTRING(@STRING,@INDICE + 1,LEN(@STRING) - @INDICE)
                  INSERT INTO @RESULTADO VALUES (@STRING_CONCATENADA)
                  SET @INDICE = CHARINDEX(',',@STRING)
            END
            SET @STRING_CONCATENADA = @STRING
            INSERT INTO @RESULTADO VALUES (@STRING_CONCATENADA)
      END
      RETURN
END