USE VAGAS_DW
GO

-- drop table VAGAS_DW.DATAS
CREATE TABLE VAGAS_DW.DATAS (DATAKEY INT IDENTITY PRIMARY KEY,
							 DATAALTKEY SMALLDATETIME,
							 DIA TINYINT,
							 MES TINYINT,
							 NOMEMES VARCHAR(15),
							 ANO SMALLINT )

SET LANGUAGE 'Brazilian'
							 
;WITH CTE_DATA 
  AS ( 
		SELECT DATEADD(YEAR,4,CONVERT(SMALLDATETIME,CONVERT(VARCHAR,GETDATE(),112))) AS DATA
		UNION ALL
		SELECT DATEADD(DAY,-1,DATA ) FROM CTE_DATA 
		WHERE DATA > DATEADD(YEAR,-17,GETDATE())
		)

INSERT INTO VAGAS_DW.DATAS 
SELECT DATA AS DATAALTKEY,
		DAY(DATA) AS DIA,
		MONTH(DATA) AS MES,
		DATENAME(MONTH,DATA) AS NOMEMES,
		YEAR(DATA) AS ANO
  FROM CTE_DATA  
ORDER BY 1
OPTION (MAXRECURSION 8000);


-- SELECT * FROM VAGAS_DW.DATAS 