USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW' AND NAME = 'SPR_OLAP_Carga_Video_Entrevista')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista]
AS
SET NOCOUNT ON


-- Limpa os registros preexistentes a carga:
DELETE FROM [VAGAS_DW].[VIDEO_ENTREVISTAS]
FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS] AS A
WHERE	EXISTS (SELECT *
				FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS] AS A1
				WHERE	A.COD_VIDEOENTREVISTA = A1.COD_VIDEOENTREVISTA) ;


INSERT INTO [VAGAS_DW].[VIDEO_ENTREVISTAS](COD_VIDEOENTREVISTA,DESCR_VIDEOENTREVISTA,CODCLI_VIDEOENTREVISTA,TEMPOLEITURA_VIDEOENTREVISTA,DATACRIACAO_VIDEOENTREVISTA)
SELECT	A.COD_VIDEOENTREVISTA,
		A.DESCR_VIDEOENTREVISTA,
		A.CODCLI_VIDEOENTREVISTA,
		A.TEMPOLEITURA_VIDEOENTREVISTA,
		A.DATACRIACAO_VIDEOENTREVISTA
FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS] AS A
WHERE	NOT EXISTS (SELECT	*
					FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS] AS A1
					WHERE	A.COD_VIDEOENTREVISTA = A1.COD_VIDEOENTREVISTA) ;