-- =============================================
-- Author: Fiama
-- Create date: 12/07/2018
-- Description: Procedure para alimentação do DW
-- =============================================

USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Triagens_Vagas' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Triagens_Vagas
GO


CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Triagens_Vagas

AS
SET NOCOUNT ON


-- Limpeza da tabela:
TRUNCATE TABLE [VAGAS_DW].[TRIAGENS_VAGAS] ;

-- CARREGAR CUBO
INSERT INTO [VAGAS_DW].[TRIAGENS_VAGAS](DATA_TRIAGEM,COD_VAGA,QTD_TRIAGENS,DATA_TRIAGEM_ANTERIOR,TEMPO_DIAS_TRIAGEM,CONTEXTO,VERSAO_TRIAGEM,COD_FUNC,COD_CLI,CLIENTE_VAGAS, QTD_CURRICULOS)
SELECT	A.DATA_TRIAGEM ,
		A.COD_VAGA ,
		A.QTD_TRIAGENS ,
		IIF(CONVERT(DATE, LAG(CONVERT(SMALLDATETIME, DATA_TRIAGEM), 1, 0) OVER(PARTITION BY COD_VAGA ORDER BY CONVERT(SMALLDATETIME, DATA_TRIAGEM) ASC)) = '19000101', DATA_TRIAGEM, CONVERT(DATE, LAG(CONVERT(SMALLDATETIME, DATA_TRIAGEM), 1, 0) OVER(PARTITION BY COD_VAGA ORDER BY CONVERT(SMALLDATETIME, DATA_TRIAGEM) ASC)))  AS DATA_TRIAGEM_ANTERIOR ,
		IIF(CONVERT(DATE, LAG(CONVERT(SMALLDATETIME, DATA_TRIAGEM), 1, 0) OVER(PARTITION BY COD_VAGA ORDER BY CONVERT(SMALLDATETIME, DATA_TRIAGEM) ASC)) = '19000101', 0, DATEDIFF(DAY, CONVERT(DATE, LAG(CONVERT(SMALLDATETIME, DATA_TRIAGEM), 1, 0) OVER(PARTITION BY COD_VAGA ORDER BY CONVERT(SMALLDATETIME, DATA_TRIAGEM) ASC)), DATA_TRIAGEM)) AS TEMPO_DIAS_TRIAGEM ,
		CONTEXTO ,
		VERSAO_TRIAGEM,
		COD_FUNC,
		COD_CLI ,
		CLIENTE_VAGAS ,
		QTD_CURRICULOS
FROM	[STAGE].[VAGAS_DW].[TMP_TRIAGENS_VAGAS] AS A ;