USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW' AND NAME = 'SPR_OLAP_Carga_Video_Entrevista')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista]
AS
SET NOCOUNT ON


-- Limpa os registros preexistentes a carga:
DELETE FROM [VAGAS_DW].[VIDEO_ENTREVISTAS]
FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS] AS A
WHERE	EXISTS (SELECT *
				FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS] AS A1
				WHERE	A.COD_VIDEOENTREVISTA = A1.COD_VIDEOENTREVISTA) ;


INSERT INTO [VAGAS_DW].[VIDEO_ENTREVISTAS](COD_VIDEOENTREVISTA,DESCRICAO,COD_CLI,TEMPO_LEITURA,DATA_CRIACAO,ID_VAGAS)
SELECT	A.COD_VIDEOENTREVISTA,
		A.DESCRICAO,
		A.COD_CLI,
		A.TEMPO_LEITURA,
		A.DATA_CRIACAO,
		A.ID_VAGAS
FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS] AS A
WHERE	NOT EXISTS (SELECT	*
					FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS] AS A1
					WHERE	A.COD_VIDEOENTREVISTA = A1.COD_VIDEOENTREVISTA) ;


-- Atualiza o ID_VAGAS:
UPDATE	[VAGAS_DW].[VIDEO_ENTREVISTAS]
SET		ID_VAGAS = B.Ident_cli
FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS] AS A		INNER JOIN [hrh-data].[dbo].[Clientes] AS B ON A.COD_CLI = B.Cod_cli ;