USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW' AND NAME = 'SPR_OLAP_Carga_Video_Entrevista_Processamento')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista_Processamento]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista_Processamento]
AS
SET NOCOUNT ON


-- Limpa os registros preexistentes a carga:
DELETE FROM [VAGAS_DW].[VIDEO_ENTREVISTAS_PROCESSAMENTO]
FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS_PROCESSAMENTO] AS A
WHERE	EXISTS (SELECT *
				FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS_PROCESSAMENTO] AS A1
				WHERE	A.COD_PROCESSAMENTO = A1.COD_PROCESSAMENTO) ;


INSERT INTO [VAGAS_DW].[VIDEO_ENTREVISTAS_PROCESSAMENTO](COD_PROCESSAMENTO,COD_CAND,DATA_PROCESSAMENTO,STATUS,AGRUPADOR,
DELETADO,COD_VIDEOENTREVISTA,COD_VAGA)
SELECT	A.COD_PROCESSAMENTO,
		A.COD_CAND,
		A.DATA_PROCESSAMENTO,
		A.STATUS,
		A.AGRUPADOR,
		A.DELETADO,
		A.COD_VIDEOENTREVISTA,
		A.COD_VAGA
FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS_PROCESSAMENTO] AS A
WHERE	NOT EXISTS (SELECT	*
					FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS_PROCESSAMENTO] AS A1
					WHERE	A.COD_PROCESSAMENTO = A1.COD_PROCESSAMENTO) ;