USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW' AND NAME = 'SPR_OLAP_Carga_Video_Entrevista_Gravacao')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista_Gravacao]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Video_Entrevista_Gravacao]
AS
SET NOCOUNT ON


-- Limpa os registros preexistentes a carga:
DELETE FROM [VAGAS_DW].[VIDEO_ENTREVISTAS_GRAVACAO]
FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS_GRAVACAO] AS A
WHERE	EXISTS (SELECT *
				FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS_GRAVACAO] AS A1
				WHERE	A.COD_GRAVACAO = A1.COD_GRAVACAO) ;


INSERT INTO [VAGAS_DW].[VIDEO_ENTREVISTAS_GRAVACAO](COD_GRAVACAO,COD_VIDEOENTREVISTA,DURACAO,DATA_ENVIO,DATA_CRIACAO)
SELECT	A.COD_GRAVACAO,
		A.COD_VIDEOENTREVISTA,
		A.DURACAO,
		A.DATA_ENVIO,
		A.DATA_CRIACAO
FROM	[STAGE].[VAGAS_DW].[TMP_VIDEO_ENTREVISTAS_GRAVACAO] AS A
WHERE	NOT EXISTS (SELECT	*
					FROM	[VAGAS_DW].[VIDEO_ENTREVISTAS_GRAVACAO] AS A1
					WHERE	A.COD_GRAVACAO = A1.COD_GRAVACAO) ;