-- =============================================
-- Author: Fiama
-- Create date: 19/12/2017
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

USE [STAGE] ;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLTP_Carga_Casos_Historico' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLTP_Carga_Casos_Historico] ;
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLTP_Carga_Casos_Historico]
AS
SET NOCOUNT ON

TRUNCATE TABLE [VAGAS_DW].[VAGAS_DW].[TMP_CASOS_HISTORICO] ;

SELECT	A.ID_CASO ,
		A.NUMERO_CASO ,
		A.VALOR_ANTERIOR ,
		A.NOVO_VALOR ,
		A.ALTERADOR ,
		IIF(A.ESTAGIO_TRANSICAO = 1, A.DATA_ALTERACAO , LAG(A.DATA_ALTERACAO, 1) OVER(ORDER BY A.NUMERO_CASO ASC, A.ESTAGIO_TRANSICAO ASC)) AS DATA_ALTERACAO_ANTERIOR ,
		A.DATA_ALTERACAO ,
		A.ESTAGIO_TRANSICAO
INTO	#TMP
FROM	[VAGAS_DW].[TMP_CASOS_HISTORICO] AS A

INSERT INTO [VAGAS_DW].[VAGAS_DW].[TMP_CASOS_HISTORICO] (ID_CASO, NUMERO_CASO, VALOR_ANTERIOR, NOVO_VALOR, ALTERADOR, DATA_ALTERACAO_ANTERIOR, DATA_ALTERACAO, ESTAGIO_TRANSICAO)
SELECT	*
FROM	#TMP ;