-- =============================================
-- Author: Fiama
-- Create date: 13/11/2017
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================
USE [STAGE] ;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLTP_Carga_Links_Transicao_Status_HomePages' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLTP_Carga_Links_Transicao_Status_HomePages] ;
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLTP_Carga_Links_Transicao_Status_HomePages]
AS
SET NOCOUNT ON


DROP TABLE IF EXISTS [stage].[VAGAS_DW].[TMP_LINKS_HOMEPAGES_TRANSICAO]
SELECT	SUBQUERY_2.ID_LINK ,
		SUBQUERY_2.NOME_LINK ,
		SUBQUERY_2.DATA_CRIACAO_ALTERACAO ,
		SUBQUERY_2.VALOR_ANTERIOR ,
		SUBQUERY_2.DATA_VALOR_ANTERIOR ,
		SUBQUERY_2.VALOR_POSTERIOR ,
		SUBQUERY_2.DATA_VALOR_POSTERIOR ,
		SUBQUERY_2.CONTROLE ,
		SUBQUERY_2.FASES
INTO	[stage].[VAGAS_DW].[TMP_LINKS_HOMEPAGES_TRANSICAO]
FROM	(
	SELECT	*
	FROM	(
		SELECT	ID_LINK,
				NOME_LINK ,
				DATA_CRIACAO_ALTERACAO ,
				VALOR_ANTERIOR ,
				IIF(CONTROLE = 1, DATA_CRIACAO_ALTERACAO, LAG(DATA_CRIACAO_ALTERACAO, 1) OVER(ORDER BY ID_LINK ASC, CONTROLE ASC)) AS DATA_VALOR_ANTERIOR ,
				VALOR_POSTERIOR ,
				DATA_CRIACAO_ALTERACAO AS DATA_VALOR_POSTERIOR ,
				 ROW_NUMBER() OVER(PARTITION BY ID_LINK ORDER BY DATA_CRIACAO_ALTERACAO) CONTROLE,
				CASE
					WHEN VALOR_ANTERIOR = 'elaboracao' AND VALOR_POSTERIOR = 'elaborando' THEN 'ELABORACAO -> ELABORANDO'
					WHEN VALOR_ANTERIOR = 'elaborando' AND VALOR_POSTERIOR = 'aprovacao' THEN 'ELABORANDO -> APROVACAO'
					WHEN VALOR_ANTERIOR = 'aprovacao'  AND VALOR_POSTERIOR = 'alteracao' THEN 'APROVACAO -> ALTERACAO'
					WHEN VALOR_ANTERIOR = 'alteracao'  AND VALOR_POSTERIOR = 'alterando' THEN 'ALTERACAO -> ALTERANDO'
					WHEN VALOR_ANTERIOR = 'alterando'  AND VALOR_POSTERIOR = 'aprovacao' THEN 'ALTERANDO -> APROVACAO'
					WHEN VALOR_ANTERIOR = 'aprovacao'  AND VALOR_POSTERIOR = 'correcao'	 THEN 'APROVACAO -> CORRECAO'
					WHEN VALOR_ANTERIOR = 'correcao'   AND VALOR_POSTERIOR = 'corrigindo' THEN 'CORRECAO -> CORRIGINDO'
					WHEN VALOR_ANTERIOR = 'corrigindo' AND VALOR_POSTERIOR = 'aprovacao'  THEN 'CORRIGINDO -> APROVACAO'
					WHEN VALOR_ANTERIOR = 'aprovacao'  AND VALOR_POSTERIOR = 'implantacao' THEN 'APROVACAO -> IMPLANTACAO'
					WHEN VALOR_ANTERIOR = 'implantacao' AND VALOR_POSTERIOR = 'implantando' THEN 'IMPLANTACAO -> IMPLANTANDO'
					WHEN VALOR_ANTERIOR = 'implantando'  AND VALOR_POSTERIOR = 'publicado' THEN 'IMPLANTANDO -> PUBLICADO'
					ELSE UPPER(CONCAT(VALOR_ANTERIOR, ' ', '->', ' ', VALOR_POSTERIOR, ' ', '[CONTRAFLUXO]'))
				END AS FASES
		FROM	[VAGAS_DW].[TMP_LINKS_TRANSICAO_STATUS] AS LinksTransicao) AS SUB
	WHERE	SUB.CONTROLE > 1  -- Desconsiderar o registro com CONTROLE = 1 (Transição de status = ELABORACAO -> ELABORANDO). Combinado com Thais Equipe homepages
) AS SUBQUERY_2 ;


TRUNCATE TABLE [VAGAS_DW].[TMP_LINKS_TRANSICAO_STATUS] ;

INSERT INTO [VAGAS_DW].[TMP_LINKS_TRANSICAO_STATUS]
SELECT *
FROM	[stage].[VAGAS_DW].[TMP_LINKS_HOMEPAGES_TRANSICAO] ;