-- =============================================
-- Author: Fiama
-- Create date: 29/10/2019
-- Description: Carga dos dados OLTP
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'SPR_OLAP_Carga_Audit_Log_PBI' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Audit_Log_PBI]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Audit_Log_PBI]
AS
SET NOCOUNT ON

DECLARE	@TIME_ZONE CHAR(6) ,
		@NAME_TIME_ZONE VARCHAR(20) ,
		@LAST_LOAD DATETIME ;
		
SET	@TIME_ZONE =  (SELECT current_utc_offset FROM sys.time_zone_info WHERE name = 'Bahia Standard Time') ;
SET	@NAME_TIME_ZONE = (SELECT name FROM sys.time_zone_info WHERE name = 'Bahia Standard Time') ;
SET	@LAST_LOAD = (SELECT MAX(CONVERT(DATETIME, SWITCHOFFSET(CONVERT(DATETIME, CREATIONTIME, 103), @TIME_ZONE)))
				  FROM	[VAGAS_DW].[PBI_AUDIT_LOG]) ;

SELECT	TOP 10
		A.ID AS ID_LOG ,
		CONVERT(DATETIME, A.CREATIONTIMEUTC, 126) AT TIME ZONE @NAME_TIME_ZONE AS DATA_LOG_UTC ,
		CONVERT(DATETIME, SWITCHOFFSET(CONVERT(DATETIME, CREATIONTIME, 103), @TIME_ZONE)) AS DATA_LOG ,
		A.OPERATION AS OPERACAO,
		A.USERID AS USUARIO,
		A.CLIENTIP AS IP_USUARIO,
		A.USERAGENT AS INFORMACOES_USUARIO,
		A.ITEMNAME AS ITEM,
		A.WORKSPACENAME AS WORKSPACE,
		A.DASHBOARDNAME AS DASHBOARD,
		A.DATASETNAME AS DATASET,
		A.REPORTNAME AS RELATÓRIO	
FROM	[VAGAS_DW].[PBI_AUDIT_LOG] AS A ;