-- =============================================
-- Author: Fiama Cristi
-- Create date: 03/09/2018
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

USE [VAGAS_DW] ;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'VAGAS_DW_SPR_OLAP_Carga_Carimbadas_Candidatos' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[VAGAS_DW_SPR_OLAP_Carga_Carimbadas_Candidatos]
GO


CREATE PROCEDURE [VAGAS_DW].[VAGAS_DW_SPR_OLAP_Carga_Carimbadas_Candidatos]
AS
SET NOCOUNT ON

TRUNCATE TABLE [VAGAS_DW].[CARIMBADAS_CANDIDATOS] ;

INSERT INTO [VAGAS_DW].[CARIMBADAS_CANDIDATOS](COD_CLI, COD_FUNC, COD_VAGA, QTD_CARIMBADAS_CAND, QTD_CANDIDATOS_CARIMBADOS, DATA_INCLUSAO_CARIMBO, DATA_EXCLUSAO_CARIMBO, CONTEXTO)
SELECT	A.COD_CLI ,
		A.COD_FUNC ,
		A.COD_VAGA ,
		A.QTD_CARIMBADAS_CAND ,
		A.QTD_CANDIDATOS_CARIMBADOS ,
		A.DATA_INCLUSAO_CARIMBO ,
		A.DATA_EXCLUSAO_CARIMBO ,
		A.CONTEXTO
FROM	[STAGE].[VAGAS_DW].[TMP_CARIMBADAS_CANDIDATOS] AS A ;