-- =============================================
-- Author: Fiama
-- Create date: 09/03/2018
-- Description: Visão mensal COHORT VAGAS FLIX.
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_VAGAS_DW_SPR_OLAP_Visao_Mensal_COHORT_FLIX' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_VAGAS_DW_SPR_OLAP_Visao_Mensal_COHORT_FLIX] ;
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_VAGAS_DW_SPR_OLAP_Visao_Mensal_COHORT_FLIX]
AS
SET NOCOUNT ON

TRUNCATE TABLE [VAGAS_DW].[VISAO_MENSAL_COHORT_FLIX] ;


-- INSERE OS DADOS NA VISÃO:
-- ESTES DADOS NÃO SÃO DO GRÁFICO COHORT, A ESTRUTURA FOI UTILIZADA PARA EXIBIRMOS NO EXCEL OS REGISTROS PERSISTENTES (QUE VOLTARAM) EM OUTRA DATA A PARTIR DA PRM_DATA_REFERENCIA:
INSERT INTO [VAGAS_DW].[VISAO_MENSAL_COHORT_FLIX] (PRM_DATA_REFERENCIA, DATA_REFERENCIA, SEQUENCIA_COHORT, GRUPO_COHORT, DIF_MESES, DATA_COHORT, QTD_CNPJS, FONTE_DADOS)
SELECT	SUBQUERY.PRM_DATA_REFERENCIA ,
		SUBQUERY.DATA_REFERENCIA ,
		SUBQUERY.SEQUENCIA_COHORT ,
		ROW_NUMBER() OVER(PARTITION BY SUBQUERY.PRM_DATA_REFERENCIA, IIF(SUBQUERY.RESTO_DIVISAO = 0, 6, SUBQUERY.RESTO_DIVISAO) ORDER BY SUBQUERY.DATA_REFERENCIA) AS GRUPO_COHORT ,
		SUBQUERY.DIF_MESES ,
		CONVERT(VARCHAR, DATEADD(MONTH, SUBQUERY.DIF_MESES, SUBQUERY.PRM_DATA_REFERENCIA), 103) AS DATA_COHORT ,
		SUBQUERY.QTD_CNPJS ,
		'DADOS PERSISTENTES BASE GOOGLE SPREADSHEET'
FROM	(
			SELECT	A.PRM_DATA_REFERENCIA ,
					A.DATA_REFERENCIA ,
					CONCAT(IIF(CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) + 1)) % 6) = 0, 6, CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) + 1)) % 6)), ' ', 'MES') AS SEQUENCIA_COHORT ,
					CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) + 1)) % 6) AS RESTO_DIVISAO ,
					DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) AS DIF_MESES ,
					COUNT(*) AS QTD_CNPJS
			FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
			WHERE	A.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE' 
GROUP BY
		A.PRM_DATA_REFERENCIA ,
		A.DATA_REFERENCIA ,
		CONCAT(IIF(CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) + 1)) % 6) = 0, 6, CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) + 1)) % 6)), ' ', 'MES') ,
		CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA) + 1)) % 6),
		DATEDIFF(MONTH, PRM_DATA_REFERENCIA, DATA_REFERENCIA)) AS SUBQUERY ;


-- Insere os dados provindos da tabela [Clientes-Login], para criação do gráfico do COHORT:
WITH CTE_PRM_DATA_LOGIN (COD_CLI, PRM_DATA_LOGIN)
AS
	(SELECT	A.CodCli_log AS COD_CLI ,
			EOMONTH(CONVERT(SMALLDATETIME, MIN(CONVERT(DATE, A.Data_log)))) AS PRM_DATA_LOGIN
	 FROM	[hrh-data].[dbo].[Clientes-Login] AS A
	 WHERE	EXISTS (SELECT	1
					FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A1
					WHERE	A.CodCli_log = A1.COD_CLI_VAGAS_EPARTNER
							AND A1.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE'
							AND A1.COD_CLI_VAGAS_EPARTNER IS NOT NULL)
	 GROUP BY
			A.CodCli_log ) ,
CTE_COHORT 
AS 
	(
		SELECT	A.PRM_DATA_LOGIN ,
				EOMONTH(CONVERT(SMALLDATETIME, CONVERT(DATE, B.Data_log))) AS DATA_LOGIN ,
				CONCAT(IIF(CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, A.PRM_DATA_LOGIN, EOMONTH(CONVERT(DATE,B.Data_log))) + 1)) % 6) = 0, 6, CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, A.PRM_DATA_LOGIN, EOMONTH(CONVERT(DATE,B.Data_log))) + 1)) % 6)), ' ', 'MES') AS SEQUENCIA_COHORT ,
				CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, A.PRM_DATA_LOGIN, EOMONTH(CONVERT(DATE,B.Data_log))) + 1)) % 6) AS RESTO_DIVISAO ,
				DATEDIFF(MONTH, A.PRM_DATA_LOGIN, CONVERT(DATE, B.Data_Log)) AS DIF_MESES ,
				COUNT(DISTINCT B.CodCli_Log) AS QTD_CNPJS
		FROM	CTE_PRM_DATA_LOGIN AS A	INNER JOIN [hrh-data].[dbo].[Clientes-Login] AS B ON A.COD_CLI = B.CodCli_Log
		GROUP BY
				A.PRM_DATA_LOGIN ,
				EOMONTH(CONVERT(SMALLDATETIME, CONVERT(DATE, B.Data_log))) ,
				CONCAT(IIF(CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, A.PRM_DATA_LOGIN, EOMONTH(CONVERT(DATE,B.Data_log))) + 1)) % 6) = 0, 6, CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, A.PRM_DATA_LOGIN, EOMONTH(CONVERT(DATE,B.Data_log))) + 1)) % 6)), ' ', 'MES') ,
				CONVERT(DECIMAL(1,0),CONVERT(DECIMAL(8,2), (DATEDIFF(MONTH, A.PRM_DATA_LOGIN, EOMONTH(CONVERT(DATE,B.Data_log))) + 1)) % 6),
				DATEDIFF(MONTH, A.PRM_DATA_LOGIN, CONVERT(DATE, B.Data_Log)) )
INSERT INTO [VAGAS_DW].[VISAO_MENSAL_COHORT_FLIX] (PRM_DATA_REFERENCIA, DATA_REFERENCIA, SEQUENCIA_COHORT, GRUPO_COHORT, DIF_MESES, DATA_COHORT, QTD_CNPJS, FONTE_DADOS)
SELECT	CTE_COHORT.PRM_DATA_LOGIN ,
		CTE_COHORT.DATA_LOGIN ,
		CTE_COHORT.SEQUENCIA_COHORT ,
		ROW_NUMBER() OVER(PARTITION BY CTE_COHORT.PRM_DATA_LOGIN, IIF(CTE_COHORT.RESTO_DIVISAO = 0, 6, CTE_COHORT.RESTO_DIVISAO) ORDER BY CTE_COHORT.DATA_LOGIN) AS GRUPO_COHORT ,
		CTE_COHORT.DIF_MESES ,
		CONVERT(VARCHAR, DATEADD(MONTH, CTE_COHORT.DIF_MESES, CTE_COHORT.PRM_DATA_LOGIN), 103) AS DATA_COHORT ,
		CTE_COHORT.QTD_CNPJS ,
		'COHORT VAGAS FLIX - LOGINS' AS FONTE_DADOS
FROM CTE_COHORT