-- EXEC VAGAS_DW.SPR_OLAP_Carga_Creditos_VAGAS
USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Creditos_VAGAS' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Creditos_VAGAS
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 31/05/2016
-- Description: Procedure para alimentação do DW
-- =============================================
CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Creditos_VAGAS 

AS
SET NOCOUNT ON

-- LIMPAR TABELA FATO
DELETE VAGAS_DW.CREDITOS_VAGAS
FROM VAGAS_DW.CREDITOS_VAGAS A
WHERE EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CREDITOS_VAGAS
				WHERE ID_VENDA_ONLINE = A.ID_VENDA_ONLINE )

INSERT INTO VAGAS_DW.CREDITOS_VAGAS
SELECT * FROM VAGAS_DW.TMP_CREDITOS_VAGAS

-- ATUALIZAR NFE BASEADO NA MESMA DATA (WESLEY)
UPDATE VAGAS_DW.CREDITOS_VAGAS SET NFE = B.NFE
FROM VAGAS_DW.CREDITOS_VAGAS A
INNER JOIN VAGAS_DW.FATURAS B ON B.COD_CLI_CRM = A.CONTA_ID
WHERE B.FLAG_PAGO = 0 -- EM ABERTO
AND B.DATA_REFERENCIA = ( SELECT MAX(DATA_REFERENCIA) FROM VAGAS_DW.FATURAS )
AND A.NFE IS NULL