USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_LEADS' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_LEADS
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 16/03/2016
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_LEADS 
AS
SET NOCOUNT ON

--DELETE VAGAS_DW.LEADS
--FROM VAGAS_DW.LEADS A
--WHERE EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_LEADS
--				WHERE ID_LEAD = A.ID_LEAD )

TRUNCATE TABLE VAGAS_DW.LEADS

---- MARCAR SE O LEAD FOI ATRELADO à OPORTUNIDADE FLEX (NECESSIDADE GADE 1)
--UPDATE VAGAS_DW.TMP_LEADS SET FLAG_CONTEM_FLEX_CREDITO = CASE WHEN B.OPORTUNIDADEID IS NOT NULL THEN 1 ELSE 0 END
--FROM VAGAS_DW.TMP_LEADS A
--OUTER APPLY ( SELECT TOP 1 * 
--			  FROM VAGAS_DW.OPORTUNIDADES 
--			  WHERE OPORTUNIDADEID = A.OPORTUNIDADE_ID
--			  AND PRODUTO_GRUPO = 'FLEX' ) B

-- Inserir novos leads
INSERT INTO VAGAS_DW.LEADS(ID_LEAD,PRIMEIRO_NOME,ULTIMO_NOME,CONTA,ORIGEM,FLAG_CONVERTIDO,SEGMENTO,USUARIO,STATUS,DATA_INCLUSAO,DATA_ALTERACAO,
EMAIL,COMO_CONHECEU_VAGAS,MOTIVO_PERDA,OPORTUNIDADE,FASE_OPORTUNIDADE,VALOR_VENDA,OPORTUNIDADE_ID,CREDITOS_VAGAS)
SELECT ID_LEAD,PRIMEIRO_NOME,ULTIMO_NOME,CONTA,ORIGEM,FLAG_CONVERTIDO,SEGMENTO,USUARIO,STATUS,
CONVERT(SMALLDATETIME,CONVERT(VARCHAR,DATA_INCLUSAO,112)),CONVERT(SMALLDATETIME,CONVERT(VARCHAR,DATA_ALTERACAO,112)),
EMAIL,COMO_CONHECEU_VAGAS,MOTIVO_PERDA,OPORTUNIDADE,FASE_OPORTUNIDADE,VALOR_VENDA,OPORTUNIDADE_ID,CREDITOS_VAGAS
FROM VAGAS_DW.TMP_LEADS

-- Regra FLAG_EMAIL_GENERICO:
UPDATE	[VAGAS_DW].[LEADS]
SET		FLAG_EMAIL_GENERICO = CASE
									WHEN (A.EMAIL IS NULL OR A.EMAIL NOT LIKE '%@%')	THEN 'SIM'
									WHEN LTRIM(RTRIM(REVERSE(SUBSTRING(REVERSE(LTRIM(RTRIM(A.EMAIL))), 1, CHARINDEX('@', REVERSE(LTRIM(RTRIM(A.EMAIL)))))))) 
																												IN (SELECT	A1.NOME_DOMINIO
																													FROM	[VAGAS_DW].[LEADS_DOMINIO_GENERICO] AS A1)
																						THEN 'SIM'
									ELSE 'NÃO'
								END
FROM	[VAGAS_DW].[LEADS] AS A ;