-- =============================================
-- Author: Fiama
-- Create date: 14/08/2019
-- Description: Script com a rotina de carga OLAP do Cubo de Login_VagasEpartner_Clientes
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW' AND NAME = 'VAGAS_DW_SPR_OLAP_Carga_Perfil_Recrutador')
DROP PROCEDURE [VAGAS_DW].[VAGAS_DW_SPR_OLAP_Carga_Perfil_Recrutador]
GO

CREATE PROCEDURE [VAGAS_DW].[VAGAS_DW_SPR_OLAP_Carga_Perfil_Recrutador]
AS
SET NOCOUNT ON

-- Remove os registros existentes na tabela temporária:
DELETE FROM [VAGAS_DW].[PERFIL_RECRUTADOR]
FROM [VAGAS_DW].[PERFIL_RECRUTADOR] AS A
WHERE EXISTS (SELECT	*
			  FROM	[VAGAS_DW].[TMP_PERFIL_RECRUTADOR] AS A1
			  WHERE	A.ID = A1.ID) ;


-- Insere os registros na tabela OLAP:
INSERT INTO [VAGAS_DW].[PERFIL_RECRUTADOR] (ID,STATUS_ASSINATURA,PLANO,DTPROX_CREDITO,QTD_CREDITO_CONTRATADO,VIGENCIA_CONTRATO,RENOVACAO,DTULTATUALIZACAO_PERFIL,COD_CLI)
SELECT	A.ID ,
		A.STATUS_ASSINATURA ,
		A.PLANO ,
		A.DTPROX_CREDITO ,
		A.QTD_CREDITO_CONTRATADO ,
		A.VIGENCIA_CONTRATO ,
		A.RENOVACAO ,
		A.DTULTATUALIZACAO_PERFIL ,
		A.COD_CLI
FROM	[VAGAS_DW].[TMP_PERFIL_RECRUTADOR] AS A ;