USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Mensagens_Enviadas_Candidatos' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Mensagens_Enviadas_Candidatos
GO

-- =============================================
-- Author: Fiama
-- Create date: 30/06/2017
-- Description: Procedure para alimentação do DW
-- =============================================
CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Mensagens_Enviadas_Candidatos

AS
SET NOCOUNT ON

DECLARE @DATA_ENVIO_MSG SMALLDATETIME = NULL

SET @DATA_ENVIO_MSG = (SELECT	MIN(A1.DATA_ENVIO_MSG) 
					   FROM		[VAGAS_DW].[TMP_MENSAGENS_ENVIADAS_CANDIDATOS] AS A1)

DELETE	[VAGAS_DW].[MENSAGENS_ENVIADAS_CANDIDATOS]
FROM	[VAGAS_DW].[MENSAGENS_ENVIADAS_CANDIDATOS] A
WHERE	DATA_ENVIO_MSG >= @DATA_ENVIO_MSG

-- CARREGAR CUBO
INSERT INTO [VAGAS_DW].[MENSAGENS_ENVIADAS_CANDIDATOS] (DATA_ENVIO_MSG, QTD_ENVIO_MSG, COD_VAGA)
SELECT	DATA_ENVIO_MSG ,
		QTD_ENVIO_MSG ,
		COD_VAGA
FROM [VAGAS_DW].[TMP_MENSAGENS_ENVIADAS_CANDIDATOS] ;