-- =============================================
-- Author: Fiama
-- Create date: 26/12/2018
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Marcos_Resultados_Chave' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Marcos_Resultados_Chave
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Marcos_Resultados_Chave]

AS
SET NOCOUNT ON

-- SEMPRE CARGA FULL
TRUNCATE TABLE [VAGAS_DW].[MARCOS_RESULTADOS_CHAVE] ;

INSERT INTO [VAGAS_DW].[MARCOS_RESULTADOS_CHAVE](NID_RESULTADO,DATA_CRIACAO_RESULTADO,NID_MARCO,NID_CICLO,RESULTADO_ESPERADO,MEDIR,DATA_RESULTADO_DISPONIVEL,RESULTADO_AFERICAO,DATA_AFERICAO,STATUS_AFERICAO,RESULTADO_CHAVE_PENDENTE)
SELECT	DISTINCT A.NID_RESULTADO ,
				 A.DATA_CRIACAO_RESULTADO ,
				 A.NID_MARCO ,
				 A.NID_CICLO ,
				 A.RESULTADO_ESPERADO ,
				 A.MEDIR ,
				 A.DATA_RESULTADO_DISPONIVEL ,
				 A.RESULTADO_AFERICAO ,
				 A.DATA_AFERICAO ,
				 CASE
					WHEN A.STATUS_AFERICAO = 'AFERIDO'
						THEN 'ATINGIDO'
					WHEN A.STATUS_AFERICAO = 'NÃO AFERIDO'
						THEN 'NÃO ATINGIDO'
					ELSE 'NÃO PREENCHIDO'
				END AS STATUS_AFERICAO ,
				 IIF(CAST(GETDATE() AS DATE) > A.DATA_RESULTADO_DISPONIVEL AND A.STATUS_AFERICAO IS NULL, 'SIM', 'NÃO') AS RESULTADO_CHAVE_PENDENTE
FROM	[STAGE].[VAGAS_DW].[TMP_MARCOS_RESULTADOS_CHAVE] AS A ;

-- Limpeza de inconsistências:
DELETE FROM [VAGAS_DW].[MARCOS_RESULTADOS_CHAVE]
FROM	[VAGAS_DW].[MARCOS_RESULTADOS_CHAVE] AS A
WHERE	( A.RESULTADO_ESPERADO IS NULL
		  AND A.MEDIR IS NULL
		  AND A.DATA_RESULTADO_DISPONIVEL IS NULL
		  AND A.RESULTADO_AFERICAO IS NULL
		  AND A.DATA_AFERICAO IS NULL
		  AND A.STATUS_AFERICAO IS NULL ) ;