-- EXEC [VAGAS_DW].[VAGAS_DW].[SPR_OLAP_Carga_Links_HomePages]
USE VAGAS_DW ;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Links_HomePages' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Links_HomePages]
GO

-- =============================================
-- Author:      Fiama dos Santos Cristi
-- Create date: 24/01/2017
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================
CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Links_HomePages]

AS
SET NOCOUNT ON


-- LIMPAR TABELA FATO:
TRUNCATE TABLE [VAGAS_DW].[VAGAS_DW].[LINKS_HOMEPAGES] ;


-- Carga dos dados na estrutura OLAP:
INSERT INTO [VAGAS_DW].[VAGAS_DW].[LINKS_HOMEPAGES] (ID_CONTA, CONTA, ID_LINK, NOME_LINK, STATUS_LINK, CATEGORIA_LINK, DATA_CRIACAO_LINK, DATA_MODIFICACAO_LINK, QTD_TRANSICOES_LINK, DATA_ULT_TRANSICAO_STATUS, QTD_STATUS_ALTERACAO, DATA_ULT_ALTERACAO_STATUS, QTD_DIAS_APROVACAO, PROPRIETARIO, DATA_SOLICITACAO, MERCADO)

SELECT	ID_CONTA,
		CONTA, 
		ID_LINK, 
		NOME_LINK, 
		STATUS_LINK, 
		CATEGORIA_LINK, 
		DATA_CRIACAO_LINK, 
		DATA_MODIFICACAO_LINK, 
		QTD_TRANSICOES_LINK, 
		DATA_ULT_TRANSICAO_STATUS, 
		QTD_STATUS_ALTERACAO, 
		DATA_ULT_ALTERACAO_STATUS, 
		QTD_DIAS_APROVACAO ,
		PROPRIETARIO ,
		DATA_SOLICITACAO ,
		IIF(ISNULL(MERCADO, 'EM BRANCO') = '', 'EM BRANCO', MERCADO) AS MERCADO
FROM	[VAGAS_DW].[VAGAS_DW].[TMP_LINKS_HOMEPAGES] ;