-- =============================================
-- Author: Fiama
-- Create date: 29/10/2019
-- Description: Carga dos dados OLTP
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM sys.objects WHERE name = 'SPR_OLAP_Carga_PBI_Audit_Log' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_PBI_Audit_Log]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_PBI_Audit_Log]
AS
SET NOCOUNT ON

DECLARE	@TIME_ZONE CHAR(6) ,
		@NAME_TIME_ZONE VARCHAR(20) ;
		
SET	@TIME_ZONE =  (SELECT current_utc_offset FROM sys.time_zone_info WHERE name = 'Bahia Standard Time') ;
SET	@NAME_TIME_ZONE = (SELECT name FROM sys.time_zone_info WHERE name = 'Bahia Standard Time') ;

DELETE FROM [VAGAS_DW].[PBI_AUDIT_LOG]
FROM [VAGAS_DW].[PBI_AUDIT_LOG] AS A
WHERE EXISTS (SELECT *
			  FROM	[VAGAS_DW].[TMP_PBI_AUDIT_LOG] AS A1
			  WHERE	A.ID = A1.ID) ;

INSERT INTO [VAGAS_DW].[PBI_AUDIT_LOG](ID,CREATIONTIMEUTC,CREATIONTIME,OPERATION,USERID,CLIENTIP,USERAGENT,ITEMNAME,WORKSPACENAME,DASHBOARDNAME,DATASETNAME,REPORTNAME)
SELECT	A.ID AS ID_LOG ,
		CONVERT(DATETIME, A.CREATIONTIMEUTC, 126) AT TIME ZONE @NAME_TIME_ZONE AS DATA_LOG_UTC ,
		CONVERT(DATETIME, SWITCHOFFSET(CONVERT(DATETIME, CREATIONTIME, 103), @TIME_ZONE)) AS DATA_LOG ,
		A.OPERATION AS OPERACAO,
		A.USERID AS USUARIO,
		A.CLIENTIP AS IP_USUARIO,
		A.USERAGENT AS CONFIG_ACESSO,
		A.ITEMNAME AS ITEM,
		A.WORKSPACENAME AS WORKSPACE,
		A.DASHBOARDNAME AS DASHBOARD,
		A.DATASETNAME AS DATASET,
		A.REPORTNAME AS RELATORIO	
FROM	[VAGAS_DW].[TMP_PBI_AUDIT_LOG] AS A ;