USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Evolucao_Marcos_Equipes' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Evolucao_Marcos_Equipes
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 05/07/2016
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Evolucao_Marcos_Equipes

AS
SET NOCOUNT ON

-- SEMPRE CARGA FULL
TRUNCATE TABLE VAGAS_DW.EVOLUCAO_MARCOS_EQUIPES

INSERT INTO VAGAS_DW.EVOLUCAO_MARCOS_EQUIPES (NOME_EQUIPE,NUMERO_MARCO,MARCO,PERC_ATINGIMENTO,CICLO,NID_MARCO,NID_CICLO)
SELECT DISTINCT 
		NOME_EQUIPE,
		NUMERO_MARCO,
		CONVERT(VARCHAR(200),MARCO),
		CONVERT(NUMERIC(4,1),PERC_ATINGIMENTO) / 100 AS PERC_ATINGIMENTO,
		CICLO,
		NID_MARCO,
		NID_CICLO
FROM VAGAS_DW.TMP_INDICADOR_MARCOS_INTRANET 

-- atualizar flag ultimo ciclo
UPDATE VAGAS_DW.EVOLUCAO_MARCOS_EQUIPES  SET FLAG_ULT_CICLO = 1
FROM VAGAS_DW.EVOLUCAO_MARCOS_EQUIPES A
WHERE CICLO = ( SELECT MAX(CICLO) 
				FROM VAGAS_DW.EVOLUCAO_MARCOS_EQUIPES  
				WHERE NOME_EQUIPE = A.NOME_EQUIPE )

				

