-- =============================================
-- Author: Fiama
-- Create date: 11/09/2018
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Funil_Demandas_SP' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Funil_Demandas_SP] ;
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Funil_Demandas_SP]
AS
SET NOCOUNT ON

-- Limpeza da tabela:
TRUNCATE TABLE [VAGAS_DW].[FUNIL_DEMANDAS_SP] ;

------------------------------------
-- Funil de Soluções Personalizadas:
------------------------------------
--SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA ,
--		'TOTAL ORCAMENTOS' AS SUB_CATEGORIA ,
--		A.DATA_REC_ORC ,
--		COUNT(*) AS QTD
--FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
--WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
--		AND A.FLAG_ROOT = 1
--		AND A.STATUS_DEMANDA IN ('CONCLUÍDA', 'CANCELADA', 'ANDAMENTO', 'ORCAMENTO')
--		AND ISNULL(A.DATA_REC_ORC, '') != ''
--GROUP BY
--		A.DATA_REC_ORC

--UNION ALL

SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO EM ANDAMENTO' AS CATEGORIA_N2  ,
		'ORCAMENTO EM ANDAMENTO' AS CATEGORIA_N3 ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
INTO	#TMP_FUNIL_DEMANDAS_SP
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA = 'ORCAMENTO'
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') = ''
		AND ISNULL(A.DATA_CAN_ORC, '') = '' 

UNION ALL

-- TOTAL DE ORÇAMENTOS CANCELADOS:
SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO CANCELADO' AS CATEGORIA_N2  ,
		'ORCAMENTO CANCELADO' AS CATEGORIA_N3 ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA = 'CANCELADA'
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') = ''
		AND ISNULL(A.DATA_CAN_ORC, '') != '' 

UNION ALL

-- TOTAL DE ORÇAMENTO CONCLUÍDO E AINDA NÃO APROVADO:
SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO CONCLUÍDO E AINDA NÃO APROVADO' AS CATEGORIA_N2  ,
		'ORCAMENTO CONCLUÍDO E AINDA NÃO APROVADO' AS CATEGORIA_N3 ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA = 'CONCLUÍDA'
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') != ''
		AND ISNULL(A.DATA_CAN_ORC, '') = ''
		AND ISNULL(A.DATA_CADASTRAMENTO, '') = '' 

UNION ALL

-- TOTAL DE PROJETOS:
--SELECT	'TOTAL PROJETOS' AS CATEGORIA_N1 ,
--		'TOTAL PROJETOS' AS CATEGORIA_N2  ,
--		A.DATA_REC_ORC ,
--		COUNT(*) AS QTD
--FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
--WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
--		AND A.FLAG_ROOT = 1
--		AND A.STATUS_DEMANDA IN ('ANDAMENTO', 'CONCLUÍDA', 'CANCELADA')
--		AND ISNULL(A.DATA_REC_ORC, '') != ''
--		AND ISNULL(A.DATA_CON_ORC, '') != ''
--		AND ISNULL(A.DATA_CAN_ORC, '') = ''
--		AND ISNULL(A.DATA_CADASTRAMENTO, '') != ''
--GROUP BY
--		A.DATA_REC_ORC 

--UNION ALL

-- TOTAL DE PROJETOS EM ANDAMENTO:
SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO -> PROJETO' AS CATEGORIA_N2 ,	
		'PROJETOS EM ANDAMENTO' AS CATEGORIA_N3  ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA = 'ANDAMENTO'
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') != ''
		AND ISNULL(A.DATA_CAN_ORC, '') = ''
		AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
		AND ISNULL(A.DATA_CONCLUSAO, '') = ''  

UNION ALL

-- TOTAL DE PROJETOS EM CANCELADOS:
SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO -> PROJETO' AS CATEGORIA_N2 ,	
		'PROJETOS CANCELADOS' AS CATEGORIA_N3  ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA = 'CANCELADA'
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') != ''
		AND ISNULL(A.DATA_CAN_ORC, '') = ''
		AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
		AND ISNULL(A.DATA_CONCLUSAO, '') != '' 

UNION ALL

-- TOTAL DE PROJETOS EM CONCLUÍDOS:
SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO -> PROJETO' AS CATEGORIA_N2 ,	
		'PROJETOS CONCLUÍDOS' AS CATEGORIA_N3  ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA = 'CONCLUÍDA'
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') != ''
		AND ISNULL(A.DATA_CAN_ORC, '') = ''
		AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
		AND ISNULL(A.DATA_CONCLUSAO, '') != '' 

UNION ALL

SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTOS SEM AGRUPAMENTO' AS CATEGORIA_N2  ,
		'ORCAMENTOS SEM AGRUPAMENTO' AS CATEGORIA_N3 ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA IN ('CONCLUÍDA', 'CANCELADA', 'ANDAMENTO', 'ORCAMENTO')
		AND ISNULL(A.DATA_REC_ORC, '') != '' 
		AND NOT ( (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA = 'ORCAMENTO'
					AND ISNULL(A.DATA_REC_ORC, '') != ''
					AND ISNULL(A.DATA_CON_ORC, '') = ''
					AND ISNULL(A.DATA_CAN_ORC, '') = '' )
				OR
				  (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA = 'CANCELADA'
					AND ISNULL(A.DATA_REC_ORC, '') != ''
					AND ISNULL(A.DATA_CON_ORC, '') = ''
					AND ISNULL(A.DATA_CAN_ORC, '') != ''  )
				 OR
				  (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA = 'CONCLUÍDA'
					AND ISNULL(A.DATA_REC_ORC, '') != ''
					AND ISNULL(A.DATA_CON_ORC, '') != ''
					AND ISNULL(A.DATA_CAN_ORC, '') = ''
					AND ISNULL(A.DATA_CADASTRAMENTO, '') = ''  )
				OR
				  (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA IN ('CONCLUÍDA', 'CANCELADA', 'ANDAMENTO')
					AND ISNULL(A.DATA_REC_ORC, '') != '' 
					AND ISNULL(A.DATA_CAN_ORC, '') = ''
					AND ISNULL(A.DATA_CON_ORC, '') != ''
					AND ISNULL(A.DATA_CADASTRAMENTO, '') != ''  ) ) -- Inclusão da sub_categoria = 'ORCAMENTO -> PROJETO'

UNION ALL

SELECT	'TOTAL ORCAMENTOS' AS CATEGORIA_N1 ,
		'ORCAMENTO -> PROJETO' AS CATEGORIA_N2 ,	
		'PROJETOS SEM AGRUPAMENTO' AS CATEGORIA_N3  ,
		A.DATA_REC_ORC ,
		A.NUMERO_DEMANDA
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Soluções Personalizadas'
		AND A.FLAG_ROOT = 1
		AND A.STATUS_DEMANDA IN ('ANDAMENTO', 'CONCLUÍDA', 'CANCELADA')
		AND ISNULL(A.DATA_REC_ORC, '') != ''
		AND ISNULL(A.DATA_CON_ORC, '') != ''
		AND ISNULL(A.DATA_CAN_ORC, '') = ''
		AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
		AND NOT (	
				  (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA = 'ANDAMENTO'
					AND ISNULL(A.DATA_REC_ORC, '') != ''
					AND ISNULL(A.DATA_CON_ORC, '') != ''
					AND ISNULL(A.DATA_CAN_ORC, '') = ''
					AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
					AND ISNULL(A.DATA_CONCLUSAO, '') = ''  )
				OR 
				  (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA = 'CANCELADA'
					AND ISNULL(A.DATA_REC_ORC, '') != ''
					AND ISNULL(A.DATA_CON_ORC, '') != ''
					AND ISNULL(A.DATA_CAN_ORC, '') = ''
					AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
					AND ISNULL(A.DATA_CONCLUSAO, '') != ''  )
				 OR
				  (
					A.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A.FLAG_ROOT = 1
					AND A.STATUS_DEMANDA = 'CONCLUÍDA'
					AND ISNULL(A.DATA_REC_ORC, '') != ''
					AND ISNULL(A.DATA_CON_ORC, '') != ''
					AND ISNULL(A.DATA_CAN_ORC, '') = ''
					AND ISNULL(A.DATA_CADASTRAMENTO, '') != '' 
					AND ISNULL(A.DATA_CONCLUSAO, '') != '' ) ) ;



-------------------------
-- Populando tabela FATO:
-------------------------
INSERT INTO [VAGAS_DW].[FUNIL_DEMANDAS_SP] (CATEGORIA_N1, CATEGORIA_N2, CATEGORIA_N3, NUMERO_DEMANDA, DATA_REC_ORC)
SELECT	A.CATEGORIA_N1 ,
		A.CATEGORIA_N2 ,
		A.CATEGORIA_N3 ,
		A.NUMERO_DEMANDA ,
		A.DATA_REC_ORC
FROM	#TMP_FUNIL_DEMANDAS_SP AS A ;