-- =============================================
-- Author: Fiama
-- Create date: 13/02/2019
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

USE [VAGAS_DW] ;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_New_Customer_Trained' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_New_Customer_Trained]
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_New_Customer_Trained]

AS
SET NOCOUNT ON

-- LIMPAR TABELA FATO:
TRUNCATE TABLE [VAGAS_DW].[NEW_CUSTOMER_TRAINED] ;

INSERT INTO [VAGAS_DW].[NEW_CUSTOMER_TRAINED](CONTA_ID, CONTA_CRM, DATA_ENTRADA, DATA_TREINAMENTO, MERCADO, HOUVE_TREINAMENTO, TEMPO_MESES_FECHADO_TREINADO,  TREINAMENTO_MESES_SLA, TEMPO_MESES_NAO_TREINADO, NOVOS_TREINADOS, NOVOSNAO_TREINADOS, INDICADOR_TREINAMENTO, FAIXA_CONTROLE_INDICADOR)
SELECT	A.CONTA_ID ,
		A.CONTA_CRM ,
		A.DATA_ENTRADA ,
		A.DATA_TREINAMENTO ,
		A.MERCADO ,
		A.HOUVE_TREINAMENTO ,
		A.TEMPO_MESES_FECHADO_TREINADO ,
		A.TREINAMENTO_MESES_SLA ,
		A.TEMPO_MESES_NAO_TREINADO ,
		A.NOVOS_TREINADOS ,
		A.NOVOSNAO_TREINADOS ,
		A.INDICADOR_TREINAMENTO ,
		A.FAIXA_CONTROLE_INDICADOR
FROM	[STAGE].[VAGAS_DW].[TMP_NEW_CUSTOMER_TRAINED] AS A ;