-- EXEC VAGAS_DW.SPR_OLAP_Carga_Funil_Candidatos
USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Funil_Candidatos' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Funil_Candidatos
GO

-- =============================================
-- Author: Fiama
-- Create date: 31/01/2017
-- Description: Procedure para alimentação do DW
-- =============================================


CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Funil_Candidatos

AS
SET NOCOUNT ON

DECLARE @DATA_REFERENCIA SMALLDATETIME

SELECT @DATA_REFERENCIA = CONVERT(SMALLDATETIME,CONVERT(VARCHAR,GETDATE(),112))

-- LIMPAR DADOS DA DATA REFERENCIA QUE SERÁ ATUALIZADA
DELETE [VAGAS_DW].[FUNIL_CANDIDATOS]
FROM [VAGAS_DW].[FUNIL_CANDIDATOS] A
WHERE DATA_REFERENCIA = @DATA_REFERENCIA


SELECT @DATA_REFERENCIA AS DATA_REFERENCIA , 
	   CASE WHEN A.ACESSO_RESTRITO = 'Não Completo [via BCC]' THEN 'PRÉ - CADASTRO'
			WHEN A.ACESSO_RESTRITO = 'Do VAGAS - BCC' THEN 'Currículo Apto' END AS TIPO_CADASTRO ,
	  DATA_CADASTRO ,
	  COUNT(*) AS QTD_CANDIDATOS
INTO	#FUNIL_CANDIDATOS
FROM	[VAGAS_DW].[VAGAS_DW].[CANDIDATOS] AS A
WHERE	A.ACESSO_RESTRITO IN ('Não Completo [via BCC]', 'Do VAGAS - BCC')
GROUP BY DATA_CADASTRO, CASE WHEN A.ACESSO_RESTRITO = 'Não Completo [via BCC]' THEN 'PRÉ - CADASTRO'
							 WHEN A.ACESSO_RESTRITO = 'Do VAGAS - BCC' THEN 'Currículo Apto' END


-- CONGELAMENTO DO FUNIL DE CANDIDATOS NA DATA REFERENCIA
INSERT INTO VAGAS_DW.FUNIL_CANDIDATOS (DATA_REFERENCIA, TIPO_CADASTRO, DATA_CADASTRO, QTD_CANDIDATOS)
SELECT	*
FROM	#FUNIL_CANDIDATOS ;