-- =============================================
-- Author: Fiama dos Santos Cristi
-- Create date: 29/10/2018
-- Description: Procedure para alimentação do DW
-- =============================================

USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'VAGAS_DW_SPR_OLAP_Carga_Creditos_VAGAS_PagSeguro' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[VAGAS_DW_SPR_OLAP_Carga_Creditos_VAGAS_PagSeguro]
GO

CREATE PROCEDURE [VAGAS_DW].[VAGAS_DW_SPR_OLAP_Carga_Creditos_VAGAS_PagSeguro]

AS
SET NOCOUNT ON

-- LIMPAR TABELA FATO
TRUNCATE TABLE [VAGAS_DW].[CREDITOS_VAGAS_PAGSEGURO] ;

-- Popular tabela FATO:
INSERT INTO [VAGAS_DW].[CREDITOS_VAGAS_PAGSEGURO](ID_COMPRA,CLIENTE_ID,USUARIO_ID,STATUS_COMPRA,DATA_INCLUSAO,DATA_ATUALIZACAO,VALOR,QTD_CREDITOS)
SELECT	A.ID_COMPRA ,
		A.CLIENTE_ID ,
		A.USUARIO_ID ,
		A.STATUS_COMPRA ,
		A.DATA_INCLUSAO ,
		A.DATA_ATUALIZACAO ,
		A.VALOR ,
		A.QTD_CREDITOS
FROM	[STAGE].[VAGAS_DW].[TMP_CREDITOS_VAGAS_PAGSEGURO] AS A