USE VAGAS_DW
GO
-- select * from vagas_dw.TMP_CANDIDATOS
-- EXEC VAGAS_DW.SPR_OLAP_Carga_Candidatos

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Candidatos' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Candidatos
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 29/09/2015
-- Description: Procedure para alimentação do DW
-- =============================================
CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Candidatos 

AS
SET NOCOUNT ON

DELETE VAGAS_DW.CANDIDATOS 
FROM VAGAS_DW.CANDIDATOS A
WHERE EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
				WHERE COD_CAND = A.COD_CAND )

-- CARREGAR CUBO
INSERT INTO VAGAS_DW.CANDIDATOS
SELECT * FROM VAGAS_DW.TMP_CANDIDATOS 

DELETE VAGAS_DW.CANDIDATOS_AREA_INTERESSE 
FROM VAGAS_DW.CANDIDATOS_AREA_INTERESSE A
WHERE EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
				WHERE COD_CAND = A.COD_CAND )

-- CARREGAR CUBO DE "AREAS DE INTERESSE"
INSERT INTO VAGAS_DW.CANDIDATOS_AREA_INTERESSE
SELECT Cod_Cand,AREA_INTERESSE_1 AS AREA_INTERESSE,1 AS ORDEM_AREA
FROM VAGAS_DW.CANDIDATOS A
WHERE AREA_INTERESSE_1 IS NOT NULL
AND EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
			 WHERE COD_CAND = A.COD_CAND )

UNION ALL

SELECT Cod_Cand,AREA_INTERESSE_2,2 AS ORDEM_AREA
FROM VAGAS_DW.CANDIDATOS A
WHERE AREA_INTERESSE_2 IS NOT NULL
AND EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
			 WHERE COD_CAND = A.COD_CAND )

UNION ALL

SELECT Cod_Cand,AREA_INTERESSE_3,3 AS ORDEM_AREA
FROM VAGAS_DW.CANDIDATOS A
WHERE AREA_INTERESSE_3 IS NOT NULL
AND EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
			 WHERE COD_CAND = A.COD_CAND )

UNION ALL

SELECT Cod_Cand,AREA_INTERESSE_4,4 AS ORDEM_AREA
FROM VAGAS_DW.CANDIDATOS A
WHERE AREA_INTERESSE_4 IS NOT NULL
AND EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
			 WHERE COD_CAND = A.COD_CAND )

UNION ALL

SELECT Cod_Cand,AREA_INTERESSE_5,5 AS ORDEM_AREA
FROM VAGAS_DW.CANDIDATOS A
WHERE AREA_INTERESSE_5 IS NOT NULL
AND EXISTS ( SELECT 1 FROM VAGAS_DW.TMP_CANDIDATOS 
			 WHERE COD_CAND = A.COD_CAND )
