USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Agenda' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Agenda
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 05/08/2016
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Agenda 
@NOME_AGENDA VARCHAR(150)

AS
SET NOCOUNT ON

-- ATUALIZAR HORAS GASTAS E O TIPO DA REUNIÃO
UPDATE VAGAS_DW.TMP_AGENDA SET QTD_HORAS = DATEDIFF(HOUR,DATA_INICIO,DATA_FIM),
							   TIPO_REUNIAO = CASE WHEN RESUMO LIKE '%MARCOS%' THEN 'Definição Marcos Estratégicos'
												   WHEN RESUMO LIKE '%ACORDO%' 
													OR ( RESUMO LIKE '%Responsabilidades%' AND RESUMO LIKE '%Equipe%' ) THEN 'Acordo da VAGAS com a Equipe'
											  ELSE 'Outros' END
FROM VAGAS_DW.TMP_AGENDA
WHERE NOME_AGENDA = @NOME_AGENDA

-- UPDATE VAGAS_DW.TMP_AGENDA SET NOME_EQUIPE_PARTICIPANTE = NULL
-- ATUALIZAR NOME_EQUIPE_PARTICIPANTE E SALA_REUNIAO
UPDATE VAGAS_DW.TMP_AGENDA SET NOME_EQUIPE_PARTICIPANTE = B1.NOME,
							   SALA_REUNIAO = C.NOME_PARTICIPANTE
FROM VAGAS_DW.TMP_AGENDA A
INNER JOIN VAGAS_DW.TMP_AGENDA_PARTICIPANTES B ON B.ID_AGENDA = A.ID_AGENDA
INNER JOIN VAGAS_DW.EQUIPES B1 ON REPLACE(B1.EMAIL,'.br','') = REPLACE(B.EMAIL,'.br','')
OUTER APPLY ( SELECT TOP 1 * 
			  FROM VAGAS_DW.TMP_AGENDA_PARTICIPANTES
			  WHERE ID_AGENDA = A.ID_AGENDA
			  AND FLAG_RECURSO = 1 ) C
WHERE TIPO_REUNIAO IN ('Definição Marcos Estratégicos','Acordo da VAGAS com a Equipe')


-- ATUALIZAR CICLO
			   
SELECT * FROM VAGAS_DW.TMP_AGENDA WHERE TIPO_REUNIAO = 'Definição Marcos Estratégicos' AND NOME_EQUIPE_PARTICIPANTE = 'Inteligência de Negócios'

WHERE RESUMO = 'Definição das Responsabilidades - Equipe Infra (continuação)' 
AND RESUMO LIKE '%Responsabilidades' AND RESUMO LIKE '%Equipe%'

SELECT * FROM VAGAS_DW.TMP_AGENDA WHERE ID_AGENDA = '7hcvp0pue1k1pumfb76pi201s4'
ALTER TABLE VAGAS_DW.TMP_AGENDA ADD SALA_REUNIAO VARCHAR(100)
SELECT * FROM VAGAS_DW.TMP_AGENDA_PARTICIPANTES WHERE ID_AGENDA = '7hcvp0pue1k1pumfb76pi201s4'