-- =============================================
-- Author: Fiama
-- Create date: 07/08/2018
-- Description: Ajustes pontuais no CUBO DEMANDAS_EQUIPES.
-- =============================================

USE [VAGAS_DW] ;
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SRP_OLAP_Carga_DEMANDAS_EQUIPES_Ajustes_Pontuais' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SRP_OLAP_Carga_DEMANDAS_EQUIPES_Ajustes_Pontuais]
GO

CREATE PROCEDURE [VAGAS_DW].[SRP_OLAP_Carga_DEMANDAS_EQUIPES_Ajustes_Pontuais]
AS
SET NOCOUNT ON

-------------------------CICLO 11---------------------------------
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		CICLO = '#Ciclo11' ,
		NOME_RELEASE = 'Semana 10 - Julho de 2018 - #Ciclo11'
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.NOME_DEMANDA_ROOT LIKE '%#Marco%#CICLO11%'
		AND A.NOME_RELEASE = 'Sem Release' ;
-------------------------CICLO 11---------------------------------

-- Ajustes pontuais pra algumas demandas concluídas no CICLO 11:
-- NUMERO_DEMANDA = 3230
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.059027778 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3230 ;


-- NUMERO_DEMANDA = 3184
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.010416667 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3184 ;


-- NUMERO_DEMANDA = 3206
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.010416667 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3206 ;


-- NUMERO_DEMANDA = 3207
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.010416667 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3207 ;


-- NUMERO_DEMANDA = 3225
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.03125 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3225 ;


-- NUMERO_DEMANDA = 3247
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.03125 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3247 ;


-- NUMERO_DEMANDA = 3261
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.0625 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3261 ;


-- NUMERO_DEMANDA = 3266
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.104166667 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3266 ;



-- NUMERO_DEMANDA = 3275
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.125 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3275 ;


-- NUMERO_DEMANDA = 3276
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.166666667 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3276 ;


-- NUMERO_DEMANDA = 3285
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 1.083333333 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3285 ;


-- NUMERO_DEMANDA = 3248
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 2.708333333 * 24
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.CICLO = '#CICLO11'
		AND A.NUMERO_DEMANDA = 3248 ;


-- NUMERO_DEMANDA = 3093
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.020833333 * 24
OUTPUT	DELETED.TEMPO_GASTO, INSERTED.TEMPO_GASTO
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.NUMERO_DEMANDA = 3093
		AND A.CICLO = '#Ciclo12' ;


-- NUMERO_DEMANDA = 3136
UPDATE	[VAGAS_DW].[DEMANDAS_EQUIPES]
SET		TEMPO_GASTO = 0.020833333 * 24
OUTPUT	DELETED.TEMPO_GASTO, INSERTED.TEMPO_GASTO
FROM	[VAGAS_DW].[DEMANDAS_EQUIPES] AS A
WHERE	A.EQUIPE_PROJETO = 'Inteligência de Negócios'
		AND A.NUMERO_DEMANDA = 3136
		AND A.CICLO = '#Ciclo12' ;