USE VAGAS_DW
GO

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Treinamentos_CRM' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Treinamentos_CRM]
GO


-- =============================================
-- Author:      Fiama dos Santos Cristi
-- Create date: 16/09/2016
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================
CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Treinamentos_CRM]

AS
SET NOCOUNT ON


-- LIMPAR TABELA FATO:
TRUNCATE TABLE [VAGAS_DW].[TREINAMENTOS_CRM] ;

INSERT INTO [VAGAS_DW].[TREINAMENTOS_CRM]
SELECT A.DATA_REFERENCIA ,
	A.ID_TREINAMENTO ,
	A.NOME_TREINAMENTO ,
	A.DATA_ENTRADA ,
	A.DATA_MODIFICACAO ,
	A.USUARIO_MODIFICOU ,
	A.USUARIO_CRIOU ,
	A.REMOVIDO ,
	A.PROPRIETARIO ,
	A.CATEGORIA ,
	A.MODULO ,
	A.DATA_REALIZACAO_INICIO ,
	A.DATA_REALIZACAO_FIM ,
	A.FORMATO ,
	A.[LOCAL] ,
	A.[STATUS] ,
	A.PRIM_INSTRUTOR ,
	A.SEG_INSTRUTOR ,
	A.CUSTO ,
	A.ACADEMIA_VAGAS ,
	A.CLIENTE_VAGAS ,
	A.TIPO_ACADEMIA_VAGAS ,
	A.MERCADO ,
	A.CONTA_ID
FROM [VAGAS_DW].[TMP_TREINAMENTOS_CRM] AS A ;