-- =============================================
-- Author: Luiz Fiama Cristi
-- Create date: 11/09/2018
-- Description: Procedure para alimentação do DW
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Demandas_Equipe_Consolidado_SP' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Demandas_Equipe_Consolidado_SP] ;
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Demandas_Equipe_Consolidado_SP]
AS
SET NOCOUNT ON

TRUNCATE TABLE [VAGAS_DW].[DEMANDAS_SP_CONSOLIDADO] ;


-------------------------------------------------------------
-- Visão consolidada das demandas de Soluções Personalizadas:
-------------------------------------------------------------
SELECT	DATEPART(YEAR, A.DATAALTKEY) AS ANO ,
		DATEPART(MONTH, A.DATAALTKEY) AS MES ,
		CHOOSE(DATEPART(MONTH, A.DATAALTKEY), 'Janeiro', 'Fevereiro', 'Março', 'Abril',	'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro') AS NOMEMES ,
		( SELECT	COUNT(DISTINCT A1.NUMERO_DEMANDA) AS QTD_ORCAMENTOS
		  FROM		[VAGAS_DW].[DEMANDAS_EQUIPES] AS A1
		  WHERE		A1.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A1.FLAG_ROOT = 1
					--AND A1.CLIENTE != 'DMRH'
					AND ISNULL(A1.DATA_REC_ORC, '') != ''
					AND DATEPART(YEAR, A.DATAALTKEY) = DATEPART(YEAR, A1.DATA_REC_ORC)
					AND DATEPART(MONTH, A.DATAALTKEY) = DATEPART(MONTH, A1.DATA_REC_ORC)) AS QTD_ORCAMENTOS ,

		( SELECT	COUNT(DISTINCT A1.NUMERO_DEMANDA) AS QTD_VIABILIDADES
		  FROM		[VAGAS_DW].[DEMANDAS_EQUIPES] AS A1
		  WHERE		A1.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A1.FLAG_ROOT = 1
					--AND A1.CLIENTE != 'DMRH'
					AND ISNULL(A1.DATA_REC_VIAB, '') != ''
					AND DATEPART(YEAR, A.DATAALTKEY) = DATEPART(YEAR, A1.DATA_REC_VIAB)
					AND DATEPART(MONTH, A.DATAALTKEY) = DATEPART(MONTH, A1.DATA_REC_VIAB)) AS QTD_VIABILIDADES ,

		( SELECT	COUNT(DISTINCT A1.NUMERO_DEMANDA) AS QTD_PROJETOS
		  FROM		[VAGAS_DW].[DEMANDAS_EQUIPES] AS A1
		  WHERE		A1.EQUIPE_PROJETO = 'Soluções Personalizadas'
					AND A1.FLAG_ROOT = 1
					--AND A1.CLIENTE != 'DMRH'
					AND ISNULL(A1.DATA_CADASTRAMENTO, '') != ''
					AND DATEPART(YEAR, A.DATAALTKEY) = DATEPART(YEAR, A1.DATA_CADASTRAMENTO)
					AND DATEPART(MONTH, A.DATAALTKEY) = DATEPART(MONTH, A1.DATA_CADASTRAMENTO)) AS QTD_PROJETOS
INTO	#TMP_DEMANDAS_SP_CONSOLIDADO
FROM	[VAGAS_DW].[DATAS] AS A
WHERE	A.DATAALTKEY >= '20170101'
GROUP BY
		DATEPART(YEAR, A.DATAALTKEY) ,
		DATEPART(MONTH, A.DATAALTKEY)
ORDER BY
		ANO ASC ,
		MES ASC ;

INSERT INTO [VAGAS_DW].[DEMANDAS_SP_CONSOLIDADO]
SELECT *
FROM	#TMP_DEMANDAS_SP_CONSOLIDADO ;

-- Limpeza das tabelas temporárias:
DROP TABLE #TMP_DEMANDAS_SP_CONSOLIDADO ;