-- =============================================
-- Author: Fiama
-- Create date: 06/03/2018
-- Description: Procedure para carga das tabelas temporárias (BD Stage) para alimentação do DW
-- =============================================

USE [VAGAS_DW] ;

IF EXISTS (SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Empresas_PG_FLIX' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Empresas_PG_FLIX] ;
GO

CREATE PROCEDURE [VAGAS_DW].[SPR_OLAP_Carga_Empresas_PG_FLIX]

AS
SET NOCOUNT ON

	-- Remoção de registros do PG:
	DELETE FROM [VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
	FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
	WHERE	A.FONTE_CNPJ = 'PostgreSQL - Termo de Aceite'

	INSERT INTO [VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX](DATA_ENTRADA, CNPJ, FONTE_CNPJ)
	SELECT	A.DATA_ENTRADA ,
			A.CNPJ ,
			'PostgreSQL - Termo de Aceite' AS FONTE_CNPJ
	FROM	[VAGAS_DW].[TMP_EMPRESAS_PG_VAGAS_FLIX] AS A ;


	-- Customização para o gráfico do PIPELINE: DATA_ENTRADA no mesmo Ano e mês da última DATA_REFERENCIA:
	DECLARE	@MAIOR_DATA_REFERENCIA SMALLDATETIME ;
	SET		@MAIOR_DATA_REFERENCIA = (SELECT	MAX(A1.DATA_REFERENCIA) FROM [VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A1)

	UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
	SET		FLAG_DT_ENT_DT_REF = (SELECT	IIF(DATEPART(YEAR, @MAIOR_DATA_REFERENCIA) = DATEPART(YEAR, A.DATA_ENTRADA)
												AND DATEPART(MONTH, @MAIOR_DATA_REFERENCIA) = DATEPART(MONTH, A.DATA_ENTRADA), 'SIM', 'NÃO'))
	FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A ;


	-- FLAG_VAGAS_EPARTNER:
	UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
	SET		FLAG_VAGAS_EPARTNER = 1
	FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
	WHERE	EXISTS (SELECT	1
					FROM	[hrh-data].[dbo].[FranqueadorxFranqueado] AS A1		INNER JOIN [hrh-data].[dbo].[Clientes] AS A2 ON A1.codclifranqueado_fcf = A2.Cod_cli
																				INNER JOIN [hrh-data].[dbo].[Divisoes] AS A3 ON A1.coddivfranqueador_fcf = A3.cod_div
														
					WHERE	A1.codclifranqueador_fcf = 65561
							AND	A.CNPJ COLLATE SQL_Latin1_General_CP1_CI_AI = A2.CGC_cli COLLATE SQL_Latin1_General_CP1_CI_AI) ;

	-- Registros provindos do PostgreSQL, que existem na fonte SPREADSHEET GOOGLE DRIVE na última DATA_REFERENCIA:
	-- FLAG_ACEITE_ULT_DATA_REF:
	UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
	SET		FLAG_ACEITE_ULT_DATA_REF = 'SIM'
	FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
	WHERE	FONTE_CNPJ = 'PostgreSQL - Termo de Aceite'
			AND EXISTS (SELECT	1
						FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A1
						WHERE	A.CNPJ = A1.CNPJ
								AND A1.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE'
								AND A1.DATA_REFERENCIA = (SELECT MAX(A1.DATA_REFERENCIA) 
														  FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A1
														  WHERE	A1.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE')) ;


-- Registros que fizeram o ACEITE ONLINE, independente da DATA_REFERENCIA:
UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
SET		QTD_TERMO_ACEITE = 1
FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
WHERE	A.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE'
		AND EXISTS (SELECT	1
					FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A1
					WHERE	A.CNPJ = A1.CNPJ
							AND A1.FONTE_CNPJ = 'PostgreSQL - Termo de Aceite') ;

UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
SET		QTD_TERMO_ACEITE = 0
FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
WHERE	QTD_TERMO_ACEITE IS NULL ;


-- Registros que estão na base do VAGAS E-PARTNER:
UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
SET		QTD_VAGAS_EPARTNER = 1
FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
WHERE	A.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE'
		AND EXISTS (SELECT	1
					FROM	[hrh-data].[dbo].[FranqueadorxFranqueado] AS A1		INNER JOIN [hrh-data].[dbo].[Clientes] AS A2 ON A1.codclifranqueado_fcf = A2.Cod_cli
																				INNER JOIN [hrh-data].[dbo].[Divisoes] AS A3 ON A1.coddivfranqueador_fcf = A3.cod_div
														
					WHERE	A1.codclifranqueador_fcf = 65561
							AND	A.CNPJ COLLATE SQL_Latin1_General_CP1_CI_AI = A2.CGC_cli COLLATE SQL_Latin1_General_CP1_CI_AI) ;

UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
SET		QTD_VAGAS_EPARTNER = 0
FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
WHERE	QTD_VAGAS_EPARTNER IS NULL ;


-- Registros que publicaram vagas:
UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
SET		QTD_PUBLICOU_VAGAS = 1
FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
WHERE	A.FONTE_CNPJ = 'SPREADSHEET GOOGLE DRIVE'
		AND EXISTS (SELECT	1
					FROM	[VAGAS_DW].[VAGAS] AS A1
					WHERE	A.COD_CLI_VAGAS_EPARTNER = A1.COD_CLI_VAGAS_FLIX) ;

UPDATE	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX]
SET		QTD_PUBLICOU_VAGAS = 0
FROM	[VAGAS_DW].[BASE_EMPRESAS_VAGAS_FLIX] AS A
WHERE	QTD_PUBLICOU_VAGAS = 0 ;