-- EXEC VAGAS_DW.SPR_OLAP_Carga_Pipeline_Vendas
USE VAGAS_DW
GO

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Pipeline_Vendas' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Pipeline_Vendas
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 07/11/2015
-- Description: Procedure para alimentação do DW

-- =============================================
CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Pipeline_Vendas

AS
SET NOCOUNT ON

DECLARE @DATA_REFERENCIA SMALLDATETIME

SELECT @DATA_REFERENCIA = CONVERT(SMALLDATETIME,CONVERT(VARCHAR,GETDATE(),112))

-- LIMPAR DADOS DA DATA REFERENCIA QUE SERÁ ATUALIZADA
DELETE [VAGAS_DW].[PIPELINE_VENDAS]
FROM [VAGAS_DW].[PIPELINE_VENDAS] A
WHERE DATA_REFERENCIA = @DATA_REFERENCIA

-- CONGELAMENTO DO PIPELINE NA DATA REFERENCIA
INSERT INTO VAGAS_DW.PIPELINE_VENDAS (DATA_REFERENCIA,CONTA,CATEGORIA_CONTA,NEGOCIO,OPORTUNIDADE,FASE,CATEGORIA_OPORTUNIDADE,DATA_CRIACAO,PROPRIETARIO
,PRODUTO,QUANTIDADE,VALOR_PRODUTO_FINAL,VALOR_OPORTUNIDADE,FIT,VALOR_REAL,RECORRENTE,PRODUTO_RECORRENTE,OPORTUNIDADE_ID,GRUPO_VENDEDOR,CONTEM_REDES
,CONTEM_FIT,TIPO_CONTA,CNAE_SECAO_ID,CNAE_SECAO,CNAE_DIVISAO_ID,CNAE_DIVISAO,CNAE_CLASSE_ID,CNAE_CLASSE,CNAE_FAIXA_FUNCIONARIOS,SEGMENTO_COMERC
,CNAE_SUBCLASSE_ID_C,CNAE_SUBCLASSE_DESCR_C,DATA_FECHAMENTO)
SELECT @DATA_REFERENCIA,Conta,Categoria,Negocio,Oportunidade,Fase,OportunidadeCategoria,DataCriacao,Proprietario,Produto,Quantidade,ValorProdutoFINAL,
OportunidadeValor,FIT,Valor_Real,RECORRENTE,PRODUTO_RECORRENTE,OportunidadeID,GRUPO_VENDEDOR,CONTEM_REDES,CONTEM_FIT,TIPO_CONTA,CNAE_SECAO_ID,
CNAE_SECAO,CNAE_DIVISAO_ID,CNAE_DIVISAO,CNAE_CLASSE_ID,CNAE_CLASSE,CNAE_FAIXA_FUNCIONARIOS,SEGMENTO_COMERC,CNAE_SUBCLASSE_ID_C,CNAE_SUBCLASSE_DESCR_C,
DATAFECHAMENTO
FROM VAGAS_DW.OPORTUNIDADES
WHERE DataCriacao >= DATEADD(MONTH,-12,GETDATE()) -- APENAS OPORTUNIDADES CRIADAS ATÉ 12 MESES DA DATA ATUAL
