-- SELECT * FROM VAGAS_DW.FATURAMENTO
-- EXEC VAGAS_DW.SPR_OLAP_Carga_Faturamento

IF EXISTS ( SELECT * FROM SYS.OBJECTS WHERE NAME = 'SPR_OLAP_Carga_Faturamento' AND SCHEMA_NAME(SCHEMA_ID) = 'VAGAS_DW')
DROP PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Faturamento
GO

-- =============================================
-- Author: Luiz Fernando Braz
-- Create date: 20/04/2016
-- Description: Procedure para alimenta��o do DW
-- =============================================
CREATE PROCEDURE VAGAS_DW.SPR_OLAP_Carga_Faturamento

AS
SET NOCOUNT ON

DELETE VAGAS_DW.FATURAMENTO
FROM VAGAS_DW.FATURAMENTO A
WHERE EXISTS ( SELECT * FROM VAGAS_DW.TMP_FATURAMENTO
				WHERE MONTH(DATA_REFERENCIA) = MONTH(A.DATA_REFERENCIA)
				AND YEAR(DATA_REFERENCIA) = YEAR(A.DATA_REFERENCIA) )

-- ATUALIZAR AGRUPAMENTOS DE PRODUTO
UPDATE VAGAS_DW.TMP_FATURAMENTO SET GRUPO_I = B.GRUPO_I,
									GRUPO_II = B.GRUPO_II
FROM VAGAS_DW.TMP_FATURAMENTO A
INNER JOIN VAGAS_DW.GRUPO_PRODUTOS_ERP B ON B.PRODUTO = A.PRODUTO

-- CARREGAR CUBO
INSERT INTO VAGAS_DW.FATURAMENTO (NUM_PEDIDO,COD_CLI_CRM,COD_CLI,CLIENTE,PRODUTO,DATA_EMISSAO,DATA_REFERENCIA,VALOR,
DATA_INICIO_VIGENCIA,DATA_FIM_VIGENCIA,GRUPO_I,GRUPO_II,FLAG_IMPORTACAO)
SELECT * FROM VAGAS_DW.TMP_FATURAMENTO

-- expurgar datas de referencia antigas (deixar apenas a �lt. de cada mes)
DELETE VAGAS_DW.FATURAMENTO 
FROM VAGAS_DW.FATURAMENTO A
WHERE DATA_REFERENCIA <> ( SELECT MAX(DATA_REFERENCIA)
						  FROM VAGAS_DW.FATURAMENTO
						  WHERE YEAR(DATA_REFERENCIA) = YEAR(A.DATA_REFERENCIA)
						  AND MONTH(DATA_REFERENCIA) = MONTH(A.DATA_REFERENCIA) )
AND ISNULL(FLAG_IMPORTACAO,0) = 0 -- Apenas registros que n�o tenha sido importados do sistema anterior ao ERP

DECLARE @ULT_DATA_REFERENCIA SMALLDATETIME

SELECT @ULT_DATA_REFERENCIA = MAX(DATA_REFERENCIA)
FROM VAGAS_DW.FATURAMENTO 
WHERE ISNULL(FLAG_IMPORTACAO,0) = 0 

-- MARCAR EXIBI��O PADR�O
UPDATE VAGAS_DW.FATURAMENTO SET FLAG_EXIBICAO_PADRAO = 1
FROM VAGAS_DW.FATURAMENTO 
WHERE DATA_REFERENCIA <= @ULT_DATA_REFERENCIA

-- DESMARCAR DATAS QUE FORAM IMPORTADAS PARA DATA FUTURAS (pedidos anteriores � entrada do ERP)
UPDATE VAGAS_DW.FATURAMENTO SET FLAG_EXIBICAO_PADRAO = 0
FROM VAGAS_DW.FATURAMENTO 
WHERE DATA_REFERENCIA > @ULT_DATA_REFERENCIA
AND ISNULL(FLAG_IMPORTACAO,0) = 1

-- CONGELAR MERCADO DE ACORDO COM O LOG DE ALTERACOES DO CRM
UPDATE VAGAS_DW.FATURAMENTO SET MERCADO_FATURADO = B.VALOR_ATUALIZADO
FROM VAGAS_DW.FATURAMENTO A
OUTER APPLY ( SELECT TOP 1 * 
              FROM VAGAS_DW.ALTERACOES_MERCADO
              WHERE CONTA_ID = A.COD_CLI_CRM
              AND DATA_ALTERACAO <= A.DATA_EMISSAO
              ORDER BY DATA_ALTERACAO DESC) B
WHERE A.DATA_EMISSAO >= '20170401' -- INICIO DAS SEGMENTACOES DE MERCADO
AND A.MERCADO_FATURADO IS NULL

-- EMPRESAS SEM REGISTRO DE ALTERACAO CONSIDERAMOS O ATUAL
UPDATE VAGAS_DW.FATURAMENTO SET MERCADO_FATURADO = B.MERCADO
FROM VAGAS_DW.FATURAMENTO A
INNER JOIN VAGAS_DW.CLIENTES B ON B.CONTA_ID = A.COD_CLI_CRM
WHERE A.DATA_EMISSAO >= '20170401' -- INICIO DAS SEGMENTACOES DE MERCADO
AND A.MERCADO_FATURADO IS NULL
AND NOT EXISTS ( SELECT * 
                 FROM VAGAS_DW.ALTERACOES_MERCADO
                 WHERE CONTA_ID = A.COD_CLI_CRM) 


-- Ajustes pontuais do financeiro
EXEC VAGAS_DW.SPR_OLAP_Carga_Faturamento_Ajustes_Pontuais

