=IF([NIVEL_CONFIABILIDADE_CANDIDATO_SOURCE] = 1; "1- ALTO";
	IF([NIVEL_CONFIABILIDADE_CANDIDATO_SOURCE] = 2; "2- MODERADO";
	IF([NIVEL_CONFIABILIDADE_CANDIDATO_SOURCE] = 3; "3- BAIXO";
	IF([NIVEL_CONFIABILIDADE_CANDIDATO_SOURCE]= 4; "4- DESCARTÁVEL";
	"SEM CPF"))))