=IF( OR( OR(DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) >= 0 && DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) <= 365;
			DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) >= 0 && DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) <= 365);
			DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) >= 0 && DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) <= 365); "1- ALTO"; 
			
	
	IF( OR( OR(DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) >= 366 && DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) <= 730;
			DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) >= 366 && DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) <= 730);
			DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) >= 366 && DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) <= 730); "2- MODERADO";
			
	IF( OR( OR(DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) >= 731 && DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) <= 1095;
			DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) >= 731 && DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) <= 1095);
			DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) >= 731 && DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) <= 1095); "3- BAIXO";

	IF( OR( OR(DATEDIFF([DATA_CADASTRO]; DATEVALUE(NOW()); DAY) > 1095;
		DATEDIFF([DATA_ULT_ATUALIZACAO]; DATEVALUE(NOW()); DAY) > 1095);
		DATEDIFF(IF(ISBLANK([DATA_ULT_LOGIN]) = TRUE(); DATEVALUE("1900-01-01"); [DATA_ULT_LOGIN]); DATEVALUE(NOW()); DAY) > 1095); "4- DESCARTÁVEL"; "NENHUM"))))