=IF([NIVEL_CONFIABILIDADE_CANDIDATO_SOURCE]<>[NIVEL_CONFIABILIDADE_CANDIDATO_MAX_SOURCE]
	&& [NIVEL_CONFIABILIDADE_CANDIDATO] <> "SEM CPF";
	 "MAIS DE 1 NÍVEL CONFIABILIDADE";
	IF([NIVEL_CONFIABILIDADE_CANDIDATO_SOURCE]=[NIVEL_CONFIABILIDADE_CANDIDATO_MAX_SOURCE]
	&& [NIVEL_CONFIABILIDADE_CANDIDATO] <> "SEM CPF";
	 "UM NÍVEL";
	"SEM CPF"))